navbar:
  - index
  - quick-start
  - docs
  - developer-guide
  - tags
  - notes
  - posts
baseURL: https://anna-docs.netlify.app
siteTitle: "anna-docs"
siteScripts:
author: anna
themeURL: "/static/style.css"
copyright: "This work is licensed under a Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International."
