name: Tests

on:
  push:
  workflow_dispatch:
  
defaults:
  run:
    shell: bash

jobs:
  test-and-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"

      - name: Run Tests
        run: go test ./...

      - name: Generate Test Coverage
        run: go test -cover ./...
